-- Auto news blog schema (applied to Supabase as migration add_news_blog_tables).
-- Kept here for reference / re-creation. Idempotent.

create table if not exists news_feeds (
  id bigint generated by default as identity primary key,
  url text not null unique,
  label text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists news_articles (
  id bigint generated by default as identity primary key,
  url text not null unique,
  title text not null,
  source_domain text,
  snippet text,
  published_at timestamptz,
  post_id bigint,
  fetched_at timestamptz not null default now()
);
create index if not exists news_articles_post_idx on news_articles(post_id);

create table if not exists blog_posts (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  body_html text not null,
  image_url text,
  image_credit text,
  image_credit_url text,
  sources jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists blog_posts_created_idx on blog_posts(created_at desc);

-- FK added separately so the tables can be created in any order.
-- alter table news_articles add constraint news_articles_post_fk
--   foreign key (post_id) references blog_posts(id) on delete set null;

-- RLS: public read on posts only; writes via service key.
alter table news_feeds enable row level security;
alter table news_articles enable row level security;
alter table blog_posts enable row level security;
-- create policy blog_posts_public_read on blog_posts for select using (true);

-- Add feeds like:
-- insert into news_feeds (url, label) values
--   ('https://www.google.com/alerts/feeds/<id>/<token>', 'refurbished phones india');
